name: Create or update Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the repo to create'
        required: true
        type: string
      is_public_repo:
        description: 'If unchecked, repo is private'
        required: true
        default: false
        type: boolean
      package_import_name:
        description: Used in imports, e.g. `from <name> import ...`
        required: true
        type: string

env:
  GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN}}

jobs:
  create-repo-if-not-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.email "yuanyeow.github@gmail.com"
          git config --global user.name "Leow Yuan Yeow"
      - env:
          GITHUB_USERNAME: ${{ github.actor }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          IS_PUBLIC_REPO: ${{ github.event.inputs.is_public_repo }}
        run: |
          bash -x run.sh create-repo-if-not-exists

  configure-repo:
    needs: [create-repo-if-not-exists]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.email "yuanyeow.github@gmail.com"
          git config --global user.name "Leow Yuan Yeow"
      - run: |
          bash -x run.sh configure-repo
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
          PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}

  open-pr-with-generated-project:
    needs: [create-repo-if-not-exists]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
            git config --global user.email "yuanyeow.github@gmail.com"
            git config --global user.name "Leow Yuan Yeow"
      - run: |
          bash -x run.sh open-pr-with-generated-project
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          PACKAGE_IMPORT_NAME: ${{ github.event.inputs.package_import_name }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
